### ISSUE TITLE
ofxUICAnvas has no member removeWidgets

### ISSUE THREAD

**Issue by underdoeg** [morethanlogic/ofxMtlMapping2D#1]
Hi

I get the following error:

../../../addons/ofxMtlMapping2D/src/controls/ofxMtlMapping2DControls.cpp:243:24: error: ‘class ofxUIScrollableCanvas’ has no member named ‘removeWidgets’

I'm using the master branch of ofxUI

**Comment by underdoeg** [comment]
Just realized that the funciton does exist in the develop branch of ofxUI. Maybe it would make sense to note this in the readme?

**Comment by smallfly** [comment]
Good point. Thanks.
