### ISSUE TITLE
need modified version ofxMSAInteractiveObject

### ISSUE THREAD

**Issue by liquidzym** [morethanlogic/ofxMtlMapping2D#6]
seems the original one missing some method,isn't it?
cheers

**Comment by smallfly** [comment]
Hi,

Yes you are right. I have just updated the [readme](https://github.com/morethanlogic/ofxMtlMapping2D/commit/b10c00b5213db3cdc706457f040ded9c5fbf45e3). Here is the version of [ofxMSAInteractiveObject](https://github.com/smallfly/ofxMSAInteractiveObject/tree/feature/coord_transformation) you need to use for now. I should soon do a PR to the main repo.

I have still few things I want to do to ofxMtlMapping2D before merging the branch develop into master. When it is done this add-on will move to our new GitHub organisation - [Dpt.](https://github.com/RDpt). 

Are you using ofxMtlMapping2D for projects? I would love to see what you use it for.

Cheers.

**Comment by smallfly** [comment]
Hi,

I got your reply via email, but it's not in this thread. Did your message got deleted?

Anyway... I'm glad to see that you find this add-on useful. No worries about the credits and thanks for adding them to the description on Vimeo.

I bet you made changes. I'm not sure how you made this using that much projectors with ofxMtlMapping2D. Would you be open to tell a bit more about what you added to the add-on and how you used it ?

Are those changes available somewhere? Pull requests are always welcome.

Cheers.

**Comment by liquidzym** [comment]
sorry,that's weird. i saw there were double post,so i just deleted one,obviously something wrong with my browser.
sure,i'll send you email. cheers.

**Comment by smallfly** [comment]
Great!
